/**
 * Post-quantum cryptography types and utilities (Issue #522).
 *
 * Defines the interface for Kyber (KEM) + Dilithium (signature) integration
 * with backward-compatible PGP support.
 */

export type PostQuantumAlgorithm = "kyber" | "dilithium";
export type KyberVariant = "kyber-512" | "kyber-768" | "kyber-1024";
export type DilithiumVariant = "dilithium-2" | "dilithium-3" | "dilithium-5";

export interface PostQuantumKey {
  id: string;
  algorithm: PostQuantumAlgorithm;
  variant: KyberVariant | DilithiumVariant;
  publicKey: string; // base64-encoded
  createdAt: string;
  isPrimary: boolean;
}

export interface HybridKeyPair {
  /** Classic PGP key (backward compat) */
  classicKeyId: string;
  /** Post-quantum key */
  pqKey: PostQuantumKey;
  /** Combined security level */
  securityLevel: "classic" | "hybrid" | "post-quantum";
}

export interface PostQuantumStatus {
  /** Whether PQC is enabled for this account */
  enabled: boolean;
  /** Active keys */
  keys: PostQuantumKey[];
  /** Migration state */
  migrationState: "not-started" | "in-progress" | "completed" | "failed";
  /** Security indicator for UI */
  securityIndicator: "classic" | "hybrid" | "post-quantum-secure";
}

export interface EncryptedMessage {
  /** Classic encrypted payload (PGP) */
  classicPayload: string;
  /** Post-quantum encrypted payload (Kyber-wrapped key) */
  pqPayload?: string;
  /** Algorithms used */
  algorithms: {
    keyEncapsulation?: KyberVariant;
    signature?: DilithiumVariant;
  };
  /** Whether this message is post-quantum secure */
  pqSecure: boolean;
}

export const PQC_CONFIG = {
  /** Default Kyber variant for key encapsulation */
  defaultKyber: "kyber-1024" as KyberVariant,
  /** Default Dilithium variant for signatures */
  defaultDilithium: "dilithium-5" as DilithiumVariant,
  /** Security levels per Kyber variant */
  kyberSecurity: {
    "kyber-512": { bits: 128, nistLevel: 1 },
    "kyber-768": { bits: 192, nistLevel: 3 },
    "kyber-1024": { bits: 256, nistLevel: 5 },
  },
  /** Security levels per Dilithium variant */
  dilithiumSecurity: {
    "dilithium-2": { bits: 128, nistLevel: 2 },
    "dilithium-3": { bits: 192, nistLevel: 3 },
    "dilithium-5": { bits: 256, nistLevel: 5 },
  },
};

/**
 * Get the security level description for display.
 */
export function getSecurityLevelDescription(level: "classic" | "hybrid" | "post-quantum-secure"): string {
  const descriptions = {
    classic: "Standard encryption (PGP)",
    hybrid: "Hybrid encryption (PGP + Post-quantum)",
    "post-quantum-secure": "Post-quantum secure (Kyber + Dilithium)",
  };
  return descriptions[level];
}

/**
 * Get the security badge color for display.
 */
export function getSecurityBadgeColor(level: "classic" | "hybrid" | "post-quantum-secure"): string {
  const colors = {
    classic: "text-gray-500",
    hybrid: "text-yellow-500",
    "post-quantum-secure": "text-green-500",
  };
  return colors[level];
}

/**
 * Check if a key variant is post-quantum secure.
 */
export function isPostQuantumSecure(variant: KyberVariant | DilithiumVariant): boolean {
  if (variant.startsWith("kyber-")) {
    return PQC_CONFIG.kyberSecurity[variant as KyberVariant].nistLevel >= 3;
  }
  if (variant.startsWith("dilithium-")) {
    return PQC_CONFIG.dilithiumSecurity[variant as DilithiumVariant].nistLevel >= 3;
  }
  return false;
}

/**
 * Generate a new hybrid key pair (placeholder for actual crypto implementation).
 */
export function generateHybridKeyPair(
  classicKeyId: string,
  kyberVariant: KyberVariant = PQC_CONFIG.defaultKyber,
  dilithiumVariant: DilithiumVariant = PQC_CONFIG.defaultDilithium
): HybridKeyPair {
  return {
    classicKeyId,
    pqKey: {
      id: `pqk-${Date.now()}`,
      algorithm: "kyber",
      variant: kyberVariant,
      publicKey: "", // Would be generated by crypto library
      createdAt: new Date().toISOString(),
      isPrimary: true,
    },
    securityLevel: "hybrid",
  };
}

/**
 * Create a post-quantum status for a new account.
 */
export function createInitialPQStatus(): PostQuantumStatus {
  return {
    enabled: false,
    keys: [],
    migrationState: "not-started",
    securityIndicator: "classic",
  };
}

/**
 * Migrate an account to post-quantum.
 */
export function migrateToPostQuantum(
  currentStatus: PostQuantumStatus,
  classicKeyId: string
): PostQuantumStatus {
  const hybridKey = generateHybridKeyPair(classicKeyId);
  return {
    ...currentStatus,
    enabled: true,
    keys: [...currentStatus.keys, hybridKey.pqKey],
    migrationState: "completed",
    securityIndicator: "hybrid",
  };
}
